# Generated by Django 4.2.14 on 2024-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_friends_friend_alter_friends_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
