# Generated by Django 4.2.14 on 2024-08-21 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_bio_user_profile_picture_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
